fix: adjusting the dockerfile order

diff --git a/desafio-01-docker/api-find-a-friend-challenge/Dockerfile b/desafio-01-docker/api-find-a-friend-challenge/Dockerfile
--- a/desafio-01-docker/api-find-a-friend-challenge/Dockerfile
+++ b/desafio-01-docker/api-find-a-friend-challenge/Dockerfile
@@ -4,8 +4,8 @@ RUN apt-get update && apt-get install -y
 RUN addgroup --gid 2001 dev && adduser --disabled-password --gecos '' --uid 2001 --ingroup dev dev
 COPY package.json package-lock.json ./
 RUN npm install
-RUN prisma generate && echo "Prisma client successfully generated!" || echo "Failed to generate Prisma client."
 COPY . .
+RUN npx prisma generate && echo "Prisma client successfully generated!" || echo "Failed to generate Prisma client."
 RUN npm run build
 RUN ls -ls build
 EXPOSE 3333
